/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/3d-scene/panorama/': RouteRecordInfo<
      '/3d-scene/panorama/',
      '/3d-scene/panorama',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/3d-scene/panorama/components/panorama-one': RouteRecordInfo<
      '/3d-scene/panorama/components/panorama-one',
      '/3d-scene/panorama/components/panorama-one',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/3d-scene/panorama/components/panorama-three': RouteRecordInfo<
      '/3d-scene/panorama/components/panorama-three',
      '/3d-scene/panorama/components/panorama-three',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/3d-scene/panorama/components/panorama-two': RouteRecordInfo<
      '/3d-scene/panorama/components/panorama-two',
      '/3d-scene/panorama/components/panorama-two',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/3d-scene/photo-sphere-viewer/': RouteRecordInfo<
      '/3d-scene/photo-sphere-viewer/',
      '/3d-scene/photo-sphere-viewer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/3d-scene/roam/': RouteRecordInfo<
      '/3d-scene/roam/',
      '/3d-scene/roam',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/3d-scene/roam/components/guide': RouteRecordInfo<
      '/3d-scene/roam/components/guide',
      '/3d-scene/roam/components/guide',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/3d-scene/roam/components/house': RouteRecordInfo<
      '/3d-scene/roam/components/house',
      '/3d-scene/roam/components/house',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/3d-scene/tile-panorama/': RouteRecordInfo<
      '/3d-scene/tile-panorama/',
      '/3d-scene/tile-panorama',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/401': RouteRecordInfo<
      '/401',
      '/401',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/arcgis/1_create-map': RouteRecordInfo<
      '/arcgis/1_create-map',
      '/arcgis/1_create-map',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/arcgis/2_custom-popup': RouteRecordInfo<
      '/arcgis/2_custom-popup',
      '/arcgis/2_custom-popup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/arcgis/3_draw-arc-by-circle': RouteRecordInfo<
      '/arcgis/3_draw-arc-by-circle',
      '/arcgis/3_draw-arc-by-circle',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/arcgis/4_draw-arc-custom': RouteRecordInfo<
      '/arcgis/4_draw-arc-custom',
      '/arcgis/4_draw-arc-custom',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/arcgis/5_feature-reduction': RouteRecordInfo<
      '/arcgis/5_feature-reduction',
      '/arcgis/5_feature-reduction',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/arcgis/6_search-address': RouteRecordInfo<
      '/arcgis/6_search-address',
      '/arcgis/6_search-address',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/arcgis/7_3d_viewshed': RouteRecordInfo<
      '/arcgis/7_3d_viewshed',
      '/arcgis/7_3d_viewshed',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/arcgis/8_camera_view': RouteRecordInfo<
      '/arcgis/8_camera_view',
      '/arcgis/8_camera_view',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/arcgis/components/CameraView': RouteRecordInfo<
      '/arcgis/components/CameraView',
      '/arcgis/components/CameraView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/arcgis/components/CustomPopup': RouteRecordInfo<
      '/arcgis/components/CustomPopup',
      '/arcgis/components/CustomPopup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/arcgis/components/SearchAddress': RouteRecordInfo<
      '/arcgis/components/SearchAddress',
      '/arcgis/components/SearchAddress',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/cesium/basic-use/': RouteRecordInfo<
      '/cesium/basic-use/',
      '/cesium/basic-use',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/cesium/drawing-route/': RouteRecordInfo<
      '/cesium/drawing-route/',
      '/cesium/drawing-route',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/cesium/drawing-route/components/distance-label': RouteRecordInfo<
      '/cesium/drawing-route/components/distance-label',
      '/cesium/drawing-route/components/distance-label',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/cesium/drawing-route/components/route-line': RouteRecordInfo<
      '/cesium/drawing-route/components/route-line',
      '/cesium/drawing-route/components/route-line',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/cesium/drawing-route/components/route-point': RouteRecordInfo<
      '/cesium/drawing-route/components/route-point',
      '/cesium/drawing-route/components/route-point',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/cesium/drawing-route/components/take-off-point': RouteRecordInfo<
      '/cesium/drawing-route/components/take-off-point',
      '/cesium/drawing-route/components/take-off-point',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/cesium/load-geojson/': RouteRecordInfo<
      '/cesium/load-geojson/',
      '/cesium/load-geojson',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/cesium/load-model/': RouteRecordInfo<
      '/cesium/load-model/',
      '/cesium/load-model',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/cesium/route-planner/': RouteRecordInfo<
      '/cesium/route-planner/',
      '/cesium/route-planner',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/cesium/route-planner/components/LargeAreaResult': RouteRecordInfo<
      '/cesium/route-planner/components/LargeAreaResult',
      '/cesium/route-planner/components/LargeAreaResult',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/cesium/route-planner/components/RouteForm': RouteRecordInfo<
      '/cesium/route-planner/components/RouteForm',
      '/cesium/route-planner/components/RouteForm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/cesium/route-planner/components/RouteInfo': RouteRecordInfo<
      '/cesium/route-planner/components/RouteInfo',
      '/cesium/route-planner/components/RouteInfo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/comp/code-block-demo/': RouteRecordInfo<
      '/comp/code-block-demo/',
      '/comp/code-block-demo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/comp/image-comparison/': RouteRecordInfo<
      '/comp/image-comparison/',
      '/comp/image-comparison',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/comp/konva-draw/': RouteRecordInfo<
      '/comp/konva-draw/',
      '/comp/konva-draw',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/comp/leafer-draw/': RouteRecordInfo<
      '/comp/leafer-draw/',
      '/comp/leafer-draw',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/comp/notice-bar-demo/': RouteRecordInfo<
      '/comp/notice-bar-demo/',
      '/comp/notice-bar-demo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/comp/upload-file-demo/': RouteRecordInfo<
      '/comp/upload-file-demo/',
      '/comp/upload-file-demo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feat/charts-roll/': RouteRecordInfo<
      '/feat/charts-roll/',
      '/feat/charts-roll',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feat/charts-roll/components/pie-chart-roll': RouteRecordInfo<
      '/feat/charts-roll/components/pie-chart-roll',
      '/feat/charts-roll/components/pie-chart-roll',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feat/charts-roll/components/table-roll': RouteRecordInfo<
      '/feat/charts-roll/components/table-roll',
      '/feat/charts-roll/components/table-roll',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feat/count-up/': RouteRecordInfo<
      '/feat/count-up/',
      '/feat/count-up',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feat/cropper-js/': RouteRecordInfo<
      '/feat/cropper-js/',
      '/feat/cropper-js',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feat/drag-layout/': RouteRecordInfo<
      '/feat/drag-layout/',
      '/feat/drag-layout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feat/music-player/': RouteRecordInfo<
      '/feat/music-player/',
      '/feat/music-player',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feat/print-js/': RouteRecordInfo<
      '/feat/print-js/',
      '/feat/print-js',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feat/qrcode/': RouteRecordInfo<
      '/feat/qrcode/',
      '/feat/qrcode',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feat/video-player/dh-sdk-player': RouteRecordInfo<
      '/feat/video-player/dh-sdk-player',
      '/feat/video-player/dh-sdk-player',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feat/video-player/easy-player': RouteRecordInfo<
      '/feat/video-player/easy-player',
      '/feat/video-player/easy-player',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feat/video-player/hk-sdk-player': RouteRecordInfo<
      '/feat/video-player/hk-sdk-player',
      '/feat/video-player/hk-sdk-player',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feat/video-player/jessibuca-player': RouteRecordInfo<
      '/feat/video-player/jessibuca-player',
      '/feat/video-player/jessibuca-player',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feat/video-player/xg-player': RouteRecordInfo<
      '/feat/video-player/xg-player',
      '/feat/video-player/xg-player',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home/': RouteRecordInfo<
      '/home/',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/i18n/': RouteRecordInfo<
      '/i18n/',
      '/i18n',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/j-components/j-dialog-demo': RouteRecordInfo<
      '/j-components/j-dialog-demo',
      '/j-components/j-dialog-demo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/j-components/j-form-demo': RouteRecordInfo<
      '/j-components/j-form-demo',
      '/j-components/j-form-demo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/j-components/j-pagination-demo': RouteRecordInfo<
      '/j-components/j-pagination-demo',
      '/j-components/j-pagination-demo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/j-components/j-table-demo': RouteRecordInfo<
      '/j-components/j-table-demo',
      '/j-components/j-table-demo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/j-components/j-table-pro-demo': RouteRecordInfo<
      '/j-components/j-table-pro-demo',
      '/j-components/j-table-pro-demo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu/menu-0/': RouteRecordInfo<
      '/menu/menu-0/',
      '/menu/menu-0',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu/menu-0/[id]': RouteRecordInfo<
      '/menu/menu-0/[id]',
      '/menu/menu-0/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/menu/menu-0/detail': RouteRecordInfo<
      '/menu/menu-0/detail',
      '/menu/menu-0/detail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu/menu-1': RouteRecordInfo<
      '/menu/menu-1',
      '/menu/menu-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu/menu-2': RouteRecordInfo<
      '/menu/menu-2',
      '/menu/menu-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu/menu-3/menu-3-1': RouteRecordInfo<
      '/menu/menu-3/menu-3-1',
      '/menu/menu-3/menu-3-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/regexps/': RouteRecordInfo<
      '/regexps/',
      '/regexps',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/unity-in-web/': RouteRecordInfo<
      '/unity-in-web/',
      '/unity-in-web',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue-echarts/pie-chart': RouteRecordInfo<
      '/vue-echarts/pie-chart',
      '/vue-echarts/pie-chart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue-echarts/water-liquid-fill': RouteRecordInfo<
      '/vue-echarts/water-liquid-fill',
      '/vue-echarts/water-liquid-fill',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue-echarts/word-cloud-chart': RouteRecordInfo<
      '/vue-echarts/word-cloud-chart',
      '/vue-echarts/word-cloud-chart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
      pathParamNames:
        | 'all'
    }
    'src/pages/3d-scene/panorama/index.vue': {
      routes:
        | '/3d-scene/panorama/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/3d-scene/panorama/components/panorama-one.vue': {
      routes:
        | '/3d-scene/panorama/components/panorama-one'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/3d-scene/panorama/components/panorama-three.vue': {
      routes:
        | '/3d-scene/panorama/components/panorama-three'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/3d-scene/panorama/components/panorama-two.vue': {
      routes:
        | '/3d-scene/panorama/components/panorama-two'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/3d-scene/photo-sphere-viewer/index.vue': {
      routes:
        | '/3d-scene/photo-sphere-viewer/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/3d-scene/roam/index.vue': {
      routes:
        | '/3d-scene/roam/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/3d-scene/roam/components/guide.vue': {
      routes:
        | '/3d-scene/roam/components/guide'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/3d-scene/roam/components/house.vue': {
      routes:
        | '/3d-scene/roam/components/house'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/3d-scene/tile-panorama/index.vue': {
      routes:
        | '/3d-scene/tile-panorama/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/401.vue': {
      routes:
        | '/401'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/arcgis/1_create-map.vue': {
      routes:
        | '/arcgis/1_create-map'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/arcgis/2_custom-popup.vue': {
      routes:
        | '/arcgis/2_custom-popup'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/arcgis/3_draw-arc-by-circle.vue': {
      routes:
        | '/arcgis/3_draw-arc-by-circle'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/arcgis/4_draw-arc-custom.vue': {
      routes:
        | '/arcgis/4_draw-arc-custom'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/arcgis/5_feature-reduction.vue': {
      routes:
        | '/arcgis/5_feature-reduction'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/arcgis/6_search-address.vue': {
      routes:
        | '/arcgis/6_search-address'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/arcgis/7_3d_viewshed.vue': {
      routes:
        | '/arcgis/7_3d_viewshed'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/arcgis/8_camera_view.vue': {
      routes:
        | '/arcgis/8_camera_view'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/arcgis/components/CameraView.vue': {
      routes:
        | '/arcgis/components/CameraView'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/arcgis/components/CustomPopup.vue': {
      routes:
        | '/arcgis/components/CustomPopup'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/arcgis/components/SearchAddress.vue': {
      routes:
        | '/arcgis/components/SearchAddress'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/cesium/basic-use/index.vue': {
      routes:
        | '/cesium/basic-use/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/cesium/drawing-route/index.vue': {
      routes:
        | '/cesium/drawing-route/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/cesium/drawing-route/components/distance-label.vue': {
      routes:
        | '/cesium/drawing-route/components/distance-label'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/cesium/drawing-route/components/route-line.vue': {
      routes:
        | '/cesium/drawing-route/components/route-line'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/cesium/drawing-route/components/route-point.vue': {
      routes:
        | '/cesium/drawing-route/components/route-point'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/cesium/drawing-route/components/take-off-point.vue': {
      routes:
        | '/cesium/drawing-route/components/take-off-point'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/cesium/load-geojson/index.vue': {
      routes:
        | '/cesium/load-geojson/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/cesium/load-model/index.vue': {
      routes:
        | '/cesium/load-model/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/cesium/route-planner/index.vue': {
      routes:
        | '/cesium/route-planner/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/cesium/route-planner/components/LargeAreaResult.vue': {
      routes:
        | '/cesium/route-planner/components/LargeAreaResult'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/cesium/route-planner/components/RouteForm.vue': {
      routes:
        | '/cesium/route-planner/components/RouteForm'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/cesium/route-planner/components/RouteInfo.vue': {
      routes:
        | '/cesium/route-planner/components/RouteInfo'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/comp/code-block-demo/index.vue': {
      routes:
        | '/comp/code-block-demo/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/comp/image-comparison/index.vue': {
      routes:
        | '/comp/image-comparison/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/comp/konva-draw/index.vue': {
      routes:
        | '/comp/konva-draw/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/comp/leafer-draw/index.vue': {
      routes:
        | '/comp/leafer-draw/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/comp/notice-bar-demo/index.vue': {
      routes:
        | '/comp/notice-bar-demo/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/comp/upload-file-demo/index.vue': {
      routes:
        | '/comp/upload-file-demo/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/feat/charts-roll/index.vue': {
      routes:
        | '/feat/charts-roll/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/feat/charts-roll/components/pie-chart-roll.vue': {
      routes:
        | '/feat/charts-roll/components/pie-chart-roll'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/feat/charts-roll/components/table-roll.vue': {
      routes:
        | '/feat/charts-roll/components/table-roll'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/feat/count-up/index.vue': {
      routes:
        | '/feat/count-up/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/feat/cropper-js/index.vue': {
      routes:
        | '/feat/cropper-js/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/feat/drag-layout/index.vue': {
      routes:
        | '/feat/drag-layout/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/feat/music-player/index.vue': {
      routes:
        | '/feat/music-player/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/feat/print-js/index.vue': {
      routes:
        | '/feat/print-js/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/feat/qrcode/index.vue': {
      routes:
        | '/feat/qrcode/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/feat/video-player/dh-sdk-player.vue': {
      routes:
        | '/feat/video-player/dh-sdk-player'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/feat/video-player/easy-player.vue': {
      routes:
        | '/feat/video-player/easy-player'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/feat/video-player/hk-sdk-player.vue': {
      routes:
        | '/feat/video-player/hk-sdk-player'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/feat/video-player/jessibuca-player.vue': {
      routes:
        | '/feat/video-player/jessibuca-player'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/feat/video-player/xg-player.vue': {
      routes:
        | '/feat/video-player/xg-player'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/home/index.vue': {
      routes:
        | '/home/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/i18n/index.vue': {
      routes:
        | '/i18n/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/j-components/j-dialog-demo.vue': {
      routes:
        | '/j-components/j-dialog-demo'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/j-components/j-form-demo.vue': {
      routes:
        | '/j-components/j-form-demo'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/j-components/j-pagination-demo.vue': {
      routes:
        | '/j-components/j-pagination-demo'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/j-components/j-table-demo.vue': {
      routes:
        | '/j-components/j-table-demo'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/j-components/j-table-pro-demo.vue': {
      routes:
        | '/j-components/j-table-pro-demo'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/menu/menu-0/index.vue': {
      routes:
        | '/menu/menu-0/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/menu/menu-0/[id].vue': {
      routes:
        | '/menu/menu-0/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/menu/menu-0/detail.vue': {
      routes:
        | '/menu/menu-0/detail'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/menu/menu-1.vue': {
      routes:
        | '/menu/menu-1'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/menu/menu-2.vue': {
      routes:
        | '/menu/menu-2'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/menu/menu-3/menu-3-1.vue': {
      routes:
        | '/menu/menu-3/menu-3-1'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/regexps/index.vue': {
      routes:
        | '/regexps/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/unity-in-web/index.vue': {
      routes:
        | '/unity-in-web/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/vue-echarts/pie-chart.vue': {
      routes:
        | '/vue-echarts/pie-chart'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/vue-echarts/water-liquid-fill.vue': {
      routes:
        | '/vue-echarts/water-liquid-fill'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/vue-echarts/word-cloud-chart.vue': {
      routes:
        | '/vue-echarts/word-cloud-chart'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
