/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/401': RouteRecordInfo<'/401', '/401', Record<never, never>, Record<never, never>>,
    '/arcgis/1_create-map': RouteRecordInfo<'/arcgis/1_create-map', '/arcgis/1_create-map', Record<never, never>, Record<never, never>>,
    '/arcgis/2_costom-popup': RouteRecordInfo<'/arcgis/2_costom-popup', '/arcgis/2_costom-popup', Record<never, never>, Record<never, never>>,
    '/arcgis/3_draw-arc-by-circle': RouteRecordInfo<'/arcgis/3_draw-arc-by-circle', '/arcgis/3_draw-arc-by-circle', Record<never, never>, Record<never, never>>,
    '/arcgis/4_draw-arc-custom': RouteRecordInfo<'/arcgis/4_draw-arc-custom', '/arcgis/4_draw-arc-custom', Record<never, never>, Record<never, never>>,
    '/arcgis/5_feature-reduction': RouteRecordInfo<'/arcgis/5_feature-reduction', '/arcgis/5_feature-reduction', Record<never, never>, Record<never, never>>,
    '/excellent-components/countUp': RouteRecordInfo<'/excellent-components/countUp', '/excellent-components/countUp', Record<never, never>, Record<never, never>>,
    '/excellent-components/noticeBar-com': RouteRecordInfo<'/excellent-components/noticeBar-com', '/excellent-components/noticeBar-com', Record<never, never>, Record<never, never>>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
    '/i18n/': RouteRecordInfo<'/i18n/', '/i18n', Record<never, never>, Record<never, never>>,
    '/j-components/j-dialog-demo': RouteRecordInfo<'/j-components/j-dialog-demo', '/j-components/j-dialog-demo', Record<never, never>, Record<never, never>>,
    '/j-components/j-form-demo': RouteRecordInfo<'/j-components/j-form-demo', '/j-components/j-form-demo', Record<never, never>, Record<never, never>>,
    '/j-components/j-pagination-demo': RouteRecordInfo<'/j-components/j-pagination-demo', '/j-components/j-pagination-demo', Record<never, never>, Record<never, never>>,
    '/j-components/j-table-demo': RouteRecordInfo<'/j-components/j-table-demo', '/j-components/j-table-demo', Record<never, never>, Record<never, never>>,
    '/j-components/j-table-pro-demo': RouteRecordInfo<'/j-components/j-table-pro-demo', '/j-components/j-table-pro-demo', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/regexps/': RouteRecordInfo<'/regexps/', '/regexps', Record<never, never>, Record<never, never>>,
    '/unity-in-web/': RouteRecordInfo<'/unity-in-web/', '/unity-in-web', Record<never, never>, Record<never, never>>,
    '/vue-echarts/pie-chart': RouteRecordInfo<'/vue-echarts/pie-chart', '/vue-echarts/pie-chart', Record<never, never>, Record<never, never>>,
    '/vue-echarts/wordCloud-chart': RouteRecordInfo<'/vue-echarts/wordCloud-chart', '/vue-echarts/wordCloud-chart', Record<never, never>, Record<never, never>>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
